import { format, parseISO } from 'date-fns';
import type { Transaction } from '../types';
import {
  canDeleteTransaction,
  getDeleteBlockedMessage,
  getKindLabel,
  getReactivateLabel,
  getTransactionKind,
  isAutoGeneratedTransaction,
  isPendingPlannedTransaction,
  isPlannedKind,
  isProcessedTransaction,
} from '../utils/transactionUtils';

function formatCurrency(value: number) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(value);
}

interface TransactionDetailModalProps {
  transaction: Transaction;
  onClose: () => void;
  onDelete: () => void;
  onFulfill?: () => void;
  onReactivate?: () => void;
}

export function TransactionDetailModal({
  transaction,
  onClose,
  onDelete,
  onFulfill,
  onReactivate,
}: TransactionDetailModalProps) {
  const kind = getTransactionKind(transaction);
  const processed = isProcessedTransaction(transaction);
  const autoGenerated = isAutoGeneratedTransaction(transaction);
  const deletable = canDeleteTransaction(transaction);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>Transaction Details</h2>
          <button type="button" className="icon-btn" onClick={onClose} aria-label="Close">
            ✕
          </button>
        </div>
        <div className="detail-modal-body">
          <div className="detail-row">
            <span className="detail-label">Type</span>
            <span className={`detail-value detail-kind ${kind} ${processed ? 'processed' : ''}`}>
              {getKindLabel(kind, processed)}
            </span>
          </div>
          <div className="detail-row">
            <span className="detail-label">Date</span>
            <span className="detail-value">{format(parseISO(transaction.date), 'MMM d, yyyy')}</span>
          </div>
          {processed && transaction.processedAt && (
            <div className="detail-row">
              <span className="detail-label">Processed On</span>
              <span className="detail-value">
                {format(parseISO(transaction.processedAt), 'MMM d, yyyy')}
              </span>
            </div>
          )}
          <div className="detail-row">
            <span className="detail-label">Amount</span>
            <span className={`detail-value detail-amount ${kind}`}>{formatCurrency(transaction.amount)}</span>
          </div>
          <div className="detail-row">
            <span className="detail-label">Counterparty</span>
            <span className="detail-value">{transaction.counterparty}</span>
          </div>
          {autoGenerated && (
            <div className="detail-note auto-generated-note">
              This record was auto-registered on Income & Outcome when the planned transaction was processed.
            </div>
          )}
          {processed && (
            <div className="detail-note processed-note">
              This planned record has been processed and is kept for history.
            </div>
          )}
          <div className="detail-row detail-row-block">
            <span className="detail-label">Details</span>
            <p className="detail-text">{transaction.details || '—'}</p>
          </div>
        </div>
        <div className="modal-actions">
          <button type="button" className="btn btn-ghost" onClick={onClose}>
            Close
          </button>
          {onFulfill && isPendingPlannedTransaction(transaction) && isPlannedKind(kind) && (
            <button type="button" className="btn btn-primary" onClick={onFulfill}>
              {kind === 'to_receive' ? 'Mark as Received' : 'Mark as Paid'}
            </button>
          )}
          {onReactivate && processed && (
            <button type="button" className="btn btn-primary" onClick={onReactivate}>
              {getReactivateLabel(kind)}
            </button>
          )}
          {deletable ? (
            <button type="button" className="btn btn-danger" onClick={onDelete}>
              Delete
            </button>
          ) : (
            <p className="detail-protected-text">{getDeleteBlockedMessage(transaction)}</p>
          )}
        </div>
      </div>
    </div>
  );
}
