import { format, parseISO } from 'date-fns';
import type { Transaction, TransactionStatus, TransactionType } from '../types';

export type TransactionKind = 'to_receive' | 'received' | 'to_pay' | 'paid';

export const TRANSACTION_KINDS: {
  kind: TransactionKind;
  type: TransactionType;
  status: TransactionStatus;
  label: string;
}[] = [
  { kind: 'to_receive', type: 'deposit', status: 'planned', label: 'To Receive' },
  { kind: 'received', type: 'deposit', status: 'actual', label: 'Received' },
  { kind: 'to_pay', type: 'withdrawal', status: 'planned', label: 'To Pay' },
  { kind: 'paid', type: 'withdrawal', status: 'actual', label: 'Paid' },
];

export function normalizeTransaction(transaction: Transaction): Transaction {
  return {
    ...transaction,
    status: transaction.status ?? 'actual',
    counterparty: transaction.counterparty ?? '',
    isAutoGenerated: transaction.isAutoGenerated ?? false,
  };
}

export function normalizeTransactions(transactions: Transaction[]): Transaction[] {
  return transactions.map(normalizeTransaction);
}

export function isProcessedTransaction(transaction: Transaction): boolean {
  return normalizeTransaction(transaction).status === 'processed';
}

export function isPendingPlannedTransaction(transaction: Transaction): boolean {
  return normalizeTransaction(transaction).status === 'planned';
}

export function isAutoGeneratedTransaction(transaction: Transaction): boolean {
  return normalizeTransaction(transaction).isAutoGenerated === true;
}

export function canDeleteTransaction(transaction: Transaction): boolean {
  const t = normalizeTransaction(transaction);
  if (t.isAutoGenerated) return false;
  if (t.status === 'processed') return false;
  return true;
}

export function getTransactionKind(transaction: Transaction): TransactionKind {
  const t = normalizeTransaction(transaction);
  if (t.type === 'deposit' && (t.status === 'planned' || t.status === 'processed')) return 'to_receive';
  if (t.type === 'deposit') return 'received';
  if (t.status === 'planned' || t.status === 'processed') return 'to_pay';
  return 'paid';
}

export function getKindLabel(kind: TransactionKind, processed = false): string {
  if (processed && kind === 'to_receive') return 'To Receive (Processed)';
  if (processed && kind === 'to_pay') return 'To Pay (Processed)';
  return TRANSACTION_KINDS.find((k) => k.kind === kind)?.label ?? kind;
}

export function kindToTypeStatus(kind: TransactionKind): {
  type: TransactionType;
  status: TransactionStatus;
} {
  const entry = TRANSACTION_KINDS.find((k) => k.kind === kind)!;
  return { type: entry.type, status: entry.status };
}

export function isActualTransaction(transaction: Transaction): boolean {
  return normalizeTransaction(transaction).status === 'actual';
}

export function getUniqueCounterparties(transactions: Transaction[]): string[] {
  const names = new Set<string>();
  transactions.forEach((t) => {
    const name = normalizeTransaction(t).counterparty.trim();
    if (name) names.add(name);
  });
  return Array.from(names).sort((a, b) => a.localeCompare(b));
}

export function filterByCounterparty(
  transactions: Transaction[],
  counterparty: string,
): Transaction[] {
  if (!counterparty) return transactions;
  return transactions.filter(
    (t) => normalizeTransaction(t).counterparty.trim() === counterparty,
  );
}

export function filterByDateRange(
  transactions: Transaction[],
  startDate: string,
  endDate: string,
): Transaction[] {
  return transactions.filter((t) => t.date >= startDate && t.date <= endDate);
}

export function sumByKind(transactions: Transaction[], kind: TransactionKind): number {
  return transactions
    .filter((t) => getTransactionKind(t) === kind)
    .reduce((sum, t) => sum + t.amount, 0);
}

export function sumPendingByKind(transactions: Transaction[], kind: TransactionKind): number {
  return transactions
    .filter((t) => getTransactionKind(t) === kind && isPendingPlannedTransaction(t))
    .reduce((sum, t) => sum + t.amount, 0);
}

export function sumActualIncome(transactions: Transaction[]): number {
  return sumByKind(transactions, 'received');
}

export function sumActualOutcome(transactions: Transaction[]): number {
  return sumByKind(transactions, 'paid');
}

export function isPlannedKind(kind: TransactionKind): boolean {
  return kind === 'to_receive' || kind === 'to_pay';
}

export function getFulfillmentKind(kind: TransactionKind): TransactionKind | null {
  if (kind === 'to_receive') return 'received';
  if (kind === 'to_pay') return 'paid';
  return null;
}

export function getFulfillLabel(kind: TransactionKind): string {
  if (kind === 'to_receive') return 'Mark as Received';
  if (kind === 'to_pay') return 'Mark as Paid';
  return '';
}

export function getReactivateLabel(kind: TransactionKind): string {
  if (kind === 'to_receive') return 'Reactivate';
  if (kind === 'to_pay') return 'Reactivate';
  return 'Reactivate';
}

export function buildAutoGeneratedDetails(
  kind: TransactionKind,
  processedDate: string,
  userDetails: string,
): string {
  const formattedDate = format(parseISO(processedDate), 'MMM d, yyyy');
  const autoNote =
    kind === 'to_receive'
      ? `[Auto-registered] Funds received on ${formattedDate}.`
      : `[Auto-registered] Funds paid on ${formattedDate}.`;

  if (userDetails.trim()) {
    return `${userDetails.trim()}\n\n${autoNote}`;
  }
  return autoNote;
}

export function getDeleteBlockedMessage(transaction: Transaction): string {
  if (isAutoGeneratedTransaction(transaction)) {
    return 'This record was auto-registered from a planned transaction and cannot be deleted directly. Reactivate the planned record to remove it.';
  }
  if (isProcessedTransaction(transaction)) {
    return 'Processed planned records cannot be deleted. Reactivate the record if you need to undo processing.';
  }
  return '';
}
