import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import { v4 as uuidv4 } from 'uuid';
import { loadData, saveData } from '../store/storage';
import type { AppData, Transaction, TransactionStatus } from '../types';
import {
  buildAutoGeneratedDetails,
  canDeleteTransaction,
  getTransactionKind,
  isPendingPlannedTransaction,
  normalizeTransactions,
} from '../utils/transactionUtils';

interface AppContextValue {
  data: AppData;
  isAuthenticated: boolean;
  login: (password: string) => boolean;
  logout: () => void;
  changePassword: (current: string, next: string) => { ok: boolean; error?: string };
  addTransaction: (input: Omit<Transaction, 'id'>) => void;
  deleteTransaction: (id: string) => { ok: boolean; error?: string };
  fulfillPlannedTransaction: (input: {
    plannedId: string;
    date: string;
    amount: number;
    counterparty: string;
    details: string;
    type: Transaction['type'];
  }) => { ok: boolean; error?: string };
  reactivatePlannedTransaction: (plannedId: string) => { ok: boolean; error?: string };
}

const AppContext = createContext<AppContextValue | null>(null);

export function AppProvider({ children }: { children: ReactNode }) {
  const [data, setData] = useState<AppData>({
    password: '123',
    transactions: [],
    debts: [],
    debtPayments: [],
  });
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    loadData().then((d) => {
      setData({
        password: d.password ?? '123',
        transactions: normalizeTransactions(d.transactions ?? []),
        debts: d.debts ?? [],
        debtPayments: d.debtPayments ?? [],
      });
      setLoaded(true);
    });
  }, []);

  useEffect(() => {
    if (loaded) {
      saveData(data);
    }
  }, [data, loaded]);

  const login = useCallback(
    (password: string) => {
      if (password === data.password) {
        setIsAuthenticated(true);
        return true;
      }
      return false;
    },
    [data.password],
  );

  const logout = useCallback(() => setIsAuthenticated(false), []);

  const changePassword = useCallback(
    (current: string, next: string) => {
      if (current !== data.password) {
        return { ok: false, error: 'Current password is incorrect.' };
      }
      if (next.length < 3) {
        return { ok: false, error: 'New password must be at least 3 characters.' };
      }
      setData((prev) => ({ ...prev, password: next }));
      return { ok: true };
    },
    [data.password],
  );

  const addTransaction = useCallback((input: Omit<Transaction, 'id'>) => {
    setData((prev) => ({
      ...prev,
      transactions: [
        ...prev.transactions,
        { ...input, id: uuidv4(), isAutoGenerated: input.isAutoGenerated ?? false },
      ].sort((a, b) => b.date.localeCompare(a.date)),
    }));
  }, []);

  const deleteTransaction = useCallback((id: string) => {
    let blocked = false;
    setData((prev) => {
      const target = prev.transactions.find((t) => t.id === id);
      if (!target || !canDeleteTransaction(target)) {
        blocked = true;
        return prev;
      }
      return {
        ...prev,
        transactions: prev.transactions.filter((t) => t.id !== id),
      };
    });
    return blocked ? { ok: false, error: 'This record cannot be deleted.' } : { ok: true };
  }, []);

  const fulfillPlannedTransaction = useCallback(
    (input: {
      plannedId: string;
      date: string;
      amount: number;
      counterparty: string;
      details: string;
      type: Transaction['type'];
    }) => {
      setData((prev) => {
        const planned = prev.transactions.find((t) => t.id === input.plannedId);
        if (!planned || !isPendingPlannedTransaction(planned)) {
          return prev;
        }

        const actualId = uuidv4();
        const kind = getTransactionKind(planned);
        const autoDetails = buildAutoGeneratedDetails(kind, input.date, input.details);

        const updatedPlanned: Transaction = {
          ...planned,
          status: 'processed',
          processedAt: input.date,
          linkedActualId: actualId,
        };

        const actual: Transaction = {
          id: actualId,
          date: input.date,
          amount: input.amount,
          type: input.type,
          status: 'actual',
          counterparty: input.counterparty,
          details: autoDetails,
          sourcePlannedId: planned.id,
          isAutoGenerated: true,
        };

        return {
          ...prev,
          transactions: prev.transactions
            .map((t) => (t.id === planned.id ? updatedPlanned : t))
            .concat(actual)
            .sort((a, b) => b.date.localeCompare(a.date)),
        };
      });

      return { ok: true };
    },
    [],
  );

  const reactivatePlannedTransaction = useCallback((plannedId: string) => {
    setData((prev) => {
      const planned = prev.transactions.find((t) => t.id === plannedId);
      if (!planned || planned.status !== 'processed') {
        return prev;
      }

      const linkedActualId = planned.linkedActualId;

      return {
        ...prev,
        transactions: prev.transactions
          .filter((t) => t.id !== linkedActualId)
          .map((t) =>
            t.id === plannedId
              ? {
                  ...t,
                  status: 'planned' as TransactionStatus,
                  processedAt: undefined,
                  linkedActualId: undefined,
                }
              : t,
          )
          .sort((a, b) => b.date.localeCompare(a.date)),
      };
    });

    return { ok: true };
  }, []);

  const value = useMemo(
    () => ({
      data,
      isAuthenticated,
      login,
      logout,
      changePassword,
      addTransaction,
      deleteTransaction,
      fulfillPlannedTransaction,
      reactivatePlannedTransaction,
    }),
    [
      data,
      isAuthenticated,
      login,
      logout,
      changePassword,
      addTransaction,
      deleteTransaction,
      fulfillPlannedTransaction,
      reactivatePlannedTransaction,
    ],
  );

  if (!loaded) {
    return (
      <div className="loading-screen">
        <div className="spinner" />
        <p>Loading LuckyDragon…</p>
      </div>
    );
  }

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}
