export type TransactionType = 'deposit' | 'withdrawal';
export type TransactionStatus = 'actual' | 'planned' | 'processed';

export interface Transaction {
  id: string;
  date: string;
  amount: number;
  type: TransactionType;
  status: TransactionStatus;
  counterparty: string;
  details: string;
  processedAt?: string;
  linkedActualId?: string;
  sourcePlannedId?: string;
  isAutoGenerated?: boolean;
}

export interface Debt {
  id: string;
  name: string;
  creditor: string;
  originalAmount: number;
  interestRate: number;
  dueDate: string;
  monthlyPayment: number;
  notes: string;
  createdDate: string;
}

export interface DebtPayment {
  id: string;
  debtId: string;
  date: string;
  amount: number;
  notes: string;
}

export interface AppData {
  password: string;
  transactions: Transaction[];
  debts: Debt[];
  debtPayments: DebtPayment[];
}

declare global {
  interface Window {
    electronAPI?: {
      loadData: () => Promise<AppData>;
      saveData: (data: AppData) => Promise<boolean>;
    };
  }
}
